language: rust

cache: cargo

branches:
  only:
    - master
    - staging
    - trying

matrix:
  fast_finish: true
  include:

  - rust: 1.34.2
    os: linux
    #if: everything!
    script: cargo build
  - rust: stable
    os: linux
    if: NOT type = pull_request