language: rust

cache: cargo

branches:
  only:
    - master
    - staging
    - trying

matrix:
  fast_finish: true
  include:

  - rust: 1.34.2
    os: linux
    #if: everything!
    script: cargo test
  - rust: stable
    os: linux
    if: NOT type = pull_request
    # script: cargo test
    script: | # cargo tarpaulin
      bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh) &&
      cargo tarpaulin --all-features --ciserver travis-ci --coveralls $TRAVIS_JOB_ID