language: rust
sudo: false
cache: cargo

rust:
- stable
os:
- linux
- osx

branches:
  only:
    - master
    - staging
    - trying

matrix:
  fast_finish: true
  include:

  - rust: stable
    os: linux
    script: |
      cargo build --verbose --all-features
  - rust: stable
    os: linux
    script: | # cargo tarpaulin
      bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh) &&
      cargo tarpaulin --all-features --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
script:
- cargo test --verbose --all-features