[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/RustSec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = [ ]
severity-threshold = "low"

[bans]
multiple-versions = "warn"
skip-tree = [
    # windows-sys minor version bumps are still incredibly tedious
    { name = "windows-sys" },
]

[licenses]
unlicensed = "warn"
allow = ["Apache-2.0", "MIT", "MPL-2.0"]
